//! grammar_replay — drive a GBNF matcher over captured bytes, byte by
//! byte, and report exactly where (or whether) it stops accepting.
//!
//! The debugging tool that cracked the 2026-07-16 "GrammarViolation
//! after the second `</parameter>`" hunt: replaying a Session's raw
//! generated bytes against the same compiled grammar separates "the
//! matcher rejects this stream" from every other way a generation can
//! end (context ceiling, token budget, stop sequences, force-EOS).
//! Sibling of `bench.py` / `profile.py` in spirit: committed because
//! it earns its keep across machines and sessions.
//!
//! Usage:
//!   # Replay captured bytes against a grammar file:
//!   cargo run --example grammar_replay -- --grammar g.gbnf --bytes raw.txt
//!
//!   # Build the grammar the way Session does for a tool-call dialect
//!   # (Qwen-XML shown; add tools via one or more --tool schema.json):
//!   cargo run --example grammar_replay -- \
//!       --dialect qwen-xml --anchor eager-thought-pre-opened \
//!       --tool count_letters.json --bytes raw.txt
//!
//! Reports, per run: the first rejected byte (offset + context) if
//! any, whether the final state is complete, and which of a few probe
//! continuations (`\n`, the remaining structural close, EOG-style
//! markers) the final state accepts.

use std::path::PathBuf;

use drama_llama::dialect::{grammar_source, Anchor, EmitOptions};
use drama_llama::{CallSyntax, GrammarState, Tool};

struct Args {
    grammar: Option<PathBuf>,
    dialect: Option<String>,
    anchor: Anchor,
    tools: Vec<PathBuf>,
    bytes: PathBuf,
    probes: Vec<String>,
}

fn parse_args() -> Args {
    let mut args = Args {
        grammar: None,
        dialect: None,
        anchor: Anchor::Eager,
        tools: Vec::new(),
        bytes: PathBuf::new(),
        probes: vec!["\n".into()],
    };
    let mut it = std::env::args().skip(1);
    while let Some(flag) = it.next() {
        let mut value = || {
            it.next().unwrap_or_else(|| {
                eprintln!("missing value for {flag}");
                std::process::exit(2);
            })
        };
        match flag.as_str() {
            "--grammar" => args.grammar = Some(PathBuf::from(value())),
            "--dialect" => args.dialect = Some(value()),
            "--anchor" => {
                args.anchor = match value().as_str() {
                    "lazy" => Anchor::Lazy,
                    "eager" => Anchor::Eager,
                    "eager-thought-pre-opened" => Anchor::EagerThoughtPreOpened,
                    other => {
                        eprintln!("unknown anchor: {other}");
                        std::process::exit(2);
                    }
                }
            }
            "--tool" => args.tools.push(PathBuf::from(value())),
            "--bytes" => args.bytes = PathBuf::from(value()),
            "--probe" => args.probes.push(value()),
            "--help" | "-h" => {
                eprintln!(
                    "grammar_replay --bytes FILE (--grammar FILE | \
                     --dialect NAME [--anchor A] --tool SCHEMA.json ...) \
                     [--probe BYTES]..."
                );
                std::process::exit(0);
            }
            other => {
                eprintln!("unknown flag: {other}");
                std::process::exit(2);
            }
        }
    }
    if args.bytes.as_os_str().is_empty() {
        eprintln!("--bytes is required (the captured byte stream)");
        std::process::exit(2);
    }
    if args.grammar.is_none() == args.dialect.is_none() {
        eprintln!("exactly one of --grammar or --dialect is required");
        std::process::exit(2);
    }
    args
}

/// A tool from a JSON file: either a bare JSON Schema (name taken from
/// the file stem) or a full `{name, description, input_schema}` object.
fn load_tool(path: &PathBuf) -> Tool {
    let text = std::fs::read_to_string(path).unwrap_or_else(|e| {
        eprintln!("read {}: {e}", path.display());
        std::process::exit(2);
    });
    let json: serde_json::Value =
        serde_json::from_str(&text).unwrap_or_else(|e| {
            eprintln!("parse {}: {e}", path.display());
            std::process::exit(2);
        });
    let (name, description, schema) = match json.get("input_schema") {
        Some(schema) => (
            json["name"].as_str().unwrap_or("tool").to_string(),
            json["description"].as_str().unwrap_or("").to_string(),
            schema.clone(),
        ),
        None => (
            path.file_stem()
                .map(|s| s.to_string_lossy().into_owned())
                .unwrap_or_else(|| "tool".into()),
            String::new(),
            json,
        ),
    };
    // Leak into 'static: the builder borrows, and a one-shot CLI has
    // no reason to fight the lifetime.
    let name: &'static str = Box::leak(name.into_boxed_str());
    let description: &'static str = Box::leak(description.into_boxed_str());
    Tool::builder(name)
        .description(description)
        .schema(schema)
        .build()
        .unwrap_or_else(|e| {
            eprintln!("build tool from {}: {e}", path.display());
            std::process::exit(2);
        })
}

fn dialect_syntax(name: &str) -> CallSyntax {
    match name {
        "qwen-xml" => CallSyntax::qwen_xml(),
        other => {
            eprintln!(
                "unknown dialect {other:?} (add it here — qwen-xml is \
                 currently wired)"
            );
            std::process::exit(2);
        }
    }
}

fn main() {
    let args = parse_args();

    let source = match (&args.grammar, &args.dialect) {
        (Some(path), None) => {
            std::fs::read_to_string(path).unwrap_or_else(|e| {
                eprintln!("read {}: {e}", path.display());
                std::process::exit(2);
            })
        }
        (None, Some(name)) => {
            let syntax = dialect_syntax(name);
            let tools: Vec<Tool> = args.tools.iter().map(load_tool).collect();
            let refs: Vec<&Tool> = tools.iter().collect();
            // `EmitOptions` is `#[non_exhaustive]`: mutate a
            // default, no literal.
            let mut opts = EmitOptions::default();
            opts.anchor = args.anchor;
            opts.parallel = !syntax.per_call_start.is_empty();
            grammar_source(&syntax, &refs, &opts).unwrap_or_else(|e| {
                eprintln!("grammar_source: {e}");
                std::process::exit(2);
            })
        }
        _ => unreachable!("validated in parse_args"),
    };

    let bytes = std::fs::read(&args.bytes).unwrap_or_else(|e| {
        eprintln!("read {}: {e}", args.bytes.display());
        std::process::exit(2);
    });

    let mut state = GrammarState::from_source(&source).unwrap_or_else(|e| {
        eprintln!("grammar parse: {e}");
        std::process::exit(2);
    });

    let mut rejected_at: Option<usize> = None;
    for (i, &b) in bytes.iter().enumerate() {
        if state.advance_bytes(&[b]).is_err() {
            rejected_at = Some(i);
            break;
        }
    }

    match rejected_at {
        Some(i) => {
            let from = i.saturating_sub(60);
            println!(
                "REJECTED at byte {i} ({:?} = {:#04x}) after ...{:?}",
                bytes[i] as char,
                bytes[i],
                String::from_utf8_lossy(&bytes[from..i]),
            );
        }
        None => {
            println!(
                "accepted all {} bytes; is_complete = {}",
                bytes.len(),
                state.is_complete()
            );
            for probe in &args.probes {
                println!(
                    "  probe {:?}: accepts = {}, completes = {}",
                    probe,
                    state.accepts_bytes(probe.as_bytes()),
                    state.completes_with(probe.as_bytes()),
                );
            }
        }
    }
}
