//! `tool_choice` → [`SamplingMode`] compiler.
//!
//! Takes a [`ToolChoice`] and the advertised [`Tool`] list, emits a GBNF
//! that forces the model's output to match the chosen shape. Rendering is
//! separate: the chat template (via `Prompt::tools`) advertises the tool
//! to the model; this module *enforces* that the model actually calls it.
//!
//! # Shapes currently supported
//!
//! The grammar targets the Llama 3.1 tool-call JSON shape, which is also
//! what HuggingFace's `transformers` tool-calling loop emits by default:
//!
//! ```json
//! {"name": "<function_name>", "parameters": {...}}
//! ```
//!
//! Some shapes (Anthropic, OpenAI) use `"arguments"` instead of
//! `"parameters"`. Configure that via
//! [`ToolChoiceOptions::arguments_field`].
//!
//! # Optional thought preamble
//!
//! Set [`ToolChoiceOptions::allow_thought`] to let the model emit a
//! `<think>…</think>` block *before* the JSON call. Useful for reasoning
//! models; a no-op for templates that don't render thought blocks on
//! re-ingest (Llama 3.1's tool-call branch ignores any surrounding
//! `content`). The grammar accepts a single thought block, then the
//! JSON call. Two balanced tags, no nesting.
//!
//! # Auto
//!
//! [`ToolChoice::Auto`] returns `None` — no sampling constraint is
//! needed because the model is free to call or not call. Pair with
//! `Prompt::tools` to advertise the tools.
//!
//! [`ToolChoice`]: misanthropic::tool::Choice
//! [`Tool`]: crate::Tool
//! [`SamplingMode`]: crate::SamplingMode

use std::fmt::Write;

use crate::{GrammarError, Prompt, SamplingMode, Tool, ToolChoice};

/// Options for [`grammar_for_tool_choice`].
#[derive(Clone, Debug)]
pub struct ToolChoiceOptions {
    /// Permit an optional `<think>…</think>` block before the JSON call.
    /// Generation-time only — survives serialization only if the caller
    /// persists the assistant content themselves.
    pub allow_thought: bool,
    /// Name of the tool-call arguments field. Llama 3.1 and HF use
    /// `"parameters"`. Anthropic / OpenAI function-calling use
    /// `"arguments"`.
    pub arguments_field: &'static str,
    /// Optional `(open, close)` tag pair that wraps the JSON tool call.
    ///
    /// Cogito, Qwen, and Hermes-style templates train the model to emit
    /// `<tool_call>{…}</tool_call>`, not bare JSON. Without the wrapper
    /// in the grammar, the model's first generated byte (`<`) is
    /// rejected and generation force-EOSes.
    ///
    /// Pass `Some(("<tool_call>\n", "\n</tool_call>"))` for cogito /
    /// Qwen-style templates. Leave as `None` for Llama 3.1-style raw
    /// JSON.
    pub wrap_tags: Option<(&'static str, &'static str)>,
    /// If `true`, constrain `parameters` to match the called tool's
    /// `input_schema` rather than accepting any JSON object.
    ///
    /// The schema-to-grammar translator covers the common case:
    /// objects with string / integer / number / boolean / null typed
    /// fields, plus string / integer / number enums. All fields are
    /// required (matches the typical `required: [...]` Anthropic
    /// shape). Unsupported schema features fall back to "any JSON
    /// value". Keep this in mind for complex nested schemas — a model
    /// can still emit a structurally valid but semantically wrong
    /// call.
    ///
    /// [`ToolChoice::Any`] with `strict_schema = true` is currently
    /// unsupported (the grammar would have to union across every
    /// tool's parameter object); setting both yields
    /// [`ToolChoiceError::AnyWithStrictSchema`]. Stick to
    /// [`ToolChoice::Method`] when you need schema enforcement.
    pub strict_schema: bool,
}

impl Default for ToolChoiceOptions {
    fn default() -> Self {
        Self {
            allow_thought: false,
            arguments_field: "parameters",
            wrap_tags: None,
            strict_schema: false,
        }
    }
}

/// Build a [`SamplingMode::Grammar`] that forces the model's output to
/// match the chosen tool-call shape.
///
/// Returns `Ok(None)` for [`ToolChoice::Auto`] — no constraint is
/// appropriate there. For [`ToolChoice::Any`] the grammar accepts any
/// of the tools in `tools`; [`ToolChoice::Method`] pins a specific
/// tool. Returns an error if the chosen tool is not in `tools`, if
/// `tools` is empty (and choice is not `Auto`), or if the generated
/// GBNF fails to compile.
pub fn grammar_for_tool_choice(
    choice: &ToolChoice,
    tools: &[Tool<'_>],
    opts: &ToolChoiceOptions,
) -> Result<Option<SamplingMode>, ToolChoiceError> {
    // Resolve which tools the grammar is allowed to pick from, and
    // optionally the single tool whose schema we enforce.
    let (names, schema_tool): (Vec<&str>, Option<&Tool<'_>>) = match choice {
        ToolChoice::Auto => return Ok(None),
        ToolChoice::Any => {
            if tools.is_empty() {
                return Err(ToolChoiceError::NoTools);
            }
            if opts.strict_schema {
                return Err(ToolChoiceError::AnyWithStrictSchema);
            }
            (tools.iter().map(|t| t.name.as_ref()).collect(), None)
        }
        ToolChoice::Method { name } => {
            let Some(tool) =
                tools.iter().find(|t| t.name.as_ref() == name.as_str())
            else {
                return Err(ToolChoiceError::UnknownTool(name.clone()));
            };
            (vec![tool.name.as_ref()], Some(tool))
        }
    };

    let source = build_grammar_source(&names, schema_tool, opts);
    let mode = SamplingMode::grammar(&source)?;
    Ok(Some(mode))
}

/// Derive the tool-choice grammar directly from a [`Prompt`]. Reads
/// `prompt.tool_choice` and `prompt.functions`; returns `Ok(None)` when
/// the prompt imposes no constraint (no `tool_choice`, `Auto`, or no
/// advertised tools).
///
/// Shorthand for the common case: the same `Prompt` that drives
/// [`ChatTemplate::render`] also drives the sampling constraint.
///
/// [`ChatTemplate::render`]: crate::ChatTemplate::render
pub fn grammar_for_prompt(
    prompt: &Prompt<'_>,
    opts: &ToolChoiceOptions,
) -> Result<Option<SamplingMode>, ToolChoiceError> {
    let Some(choice) = prompt.tool_choice.as_ref() else {
        return Ok(None);
    };
    let tools: &[Tool<'_>] = prompt.functions.as_deref().unwrap_or(&[]);
    grammar_for_tool_choice(choice, tools, opts)
}

/// Debug-only accessor for the compiled GBNF text. Kept public so the
/// `strawberry` example can `--verbose` the grammar; callers generally
/// don't need this.
#[doc(hidden)]
pub fn build_grammar_source_for_debug(
    names: &[&str],
    schema_tool: Option<&Tool<'_>>,
    opts: &ToolChoiceOptions,
) -> String {
    build_grammar_source(names, schema_tool, opts)
}

/// Emit the GBNF source text for a tool-choice constraint.
///
/// When `schema_tool` is `Some` and [`ToolChoiceOptions::strict_schema`]
/// is true, the `parameters` value is constrained to the tool's
/// `input_schema`. Otherwise the arguments accept any JSON object.
///
/// Kept pub(crate) + exposed through tests so the generated grammar can
/// be inspected directly without constructing a full [`SamplingMode`].
pub(crate) fn build_grammar_source(
    names: &[&str],
    schema_tool: Option<&Tool<'_>>,
    opts: &ToolChoiceOptions,
) -> String {
    let mut src = String::with_capacity(1024);

    // Root rule: optional thought block, then (optionally wrapped) call.
    let wrapped_call = if opts.wrap_tags.is_some() {
        "wrapped_call"
    } else {
        "call"
    };
    if opts.allow_thought {
        let _ = writeln!(src, "root ::= thought? ws {wrapped_call}");
        let _ = writeln!(src, r#"thought ::= "<think>" think_body "</think>""#);
        let _ = writeln!(src, r#"think_body ::= think_char*"#);
        let _ = writeln!(src, r#"think_char ::= [^<]"#);
    } else {
        let _ = writeln!(src, "root ::= ws {wrapped_call}");
    }
    if let Some((open, close)) = opts.wrap_tags {
        // Model emits `<open>\n{…}\n</close>` in its trained format.
        // We accept any whitespace around the JSON to tolerate minor
        // layout drift. The literal tag text is escaped to survive
        // being embedded in a GBNF string literal.
        let open_lit = escape_for_gbnf_string(open);
        let close_lit = escape_for_gbnf_string(close);
        let _ = writeln!(
            src,
            r#"wrapped_call ::= "{open_lit}" ws call ws "{close_lit}""#
        );
    }

    // Pick the rule name for the arguments value: `object` for the
    // permissive case, `args` for schema-constrained.
    let args_rule = if opts.strict_schema && schema_tool.is_some() {
        "args"
    } else {
        "object"
    };

    // The tool call: `{"name": <chosen>, "<args>": <args_rule>}`.
    let _ = writeln!(
        src,
        r#"call ::= "{{" ws "\"name\"" ws ":" ws name_choice ws "," ws "\"{arg}\"" ws ":" ws {args_rule} ws "}}""#,
        arg = opts.arguments_field,
        args_rule = args_rule,
    );

    // Alternation over the allowed function names, each quoted.
    let mut alt = String::new();
    for (i, n) in names.iter().enumerate() {
        if i > 0 {
            alt.push_str(" | ");
        }
        let escaped = n.replace('"', r#"\""#);
        write!(alt, r#""\"{escaped}\"""#).unwrap();
    }
    let _ = writeln!(src, r#"name_choice ::= {alt}"#);

    // If strict schema is on, emit the `args` rule derived from the
    // tool's input_schema. Otherwise fall through to the permissive
    // JSON grammar below (which defines `object`).
    if opts.strict_schema {
        if let Some(tool) = schema_tool {
            schema_to_gbnf(&tool.schema, "args", &mut src);
        }
    }

    // Standard JSON grammar — RFC 8259-ish, enough for tool arguments.
    src.push_str(JSON_GRAMMAR);

    src
}

/// Escape a Rust string so it can be embedded inside a GBNF `"..."`
/// literal. Handles the escapes our GBNF lexer recognizes.
fn escape_for_gbnf_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str(r"\\"),
            '"' => out.push_str(r#"\""#),
            '\n' => out.push_str(r"\n"),
            '\r' => out.push_str(r"\r"),
            '\t' => out.push_str(r"\t"),
            _ => out.push(c),
        }
    }
    out
}

/// Emit GBNF rules that constrain a JSON value to `schema`. The
/// top-level rule will be named `rule_name`; anonymous helpers get
/// names like `{rule_name}__<n>`.
///
/// Supports the subset of JSON Schema common in tool schemas:
///
/// * `type: object` with `properties` + `required`. Required fields
///   are emitted in their schema order; optional fields are ignored
///   (the generated object MUST have exactly the required set).
/// * `type: string | integer | number | boolean | null`.
/// * `enum` (string / integer / number) → alternation of literals.
///
/// Anything else falls back to a reference to `value` (the permissive
/// JSON value rule defined by [`JSON_GRAMMAR`]).
fn schema_to_gbnf(
    schema: &serde_json::Value,
    rule_name: &str,
    out: &mut String,
) {
    let mut counter: usize = 0;
    emit_schema_rule(schema, rule_name, out, &mut counter);
}

fn emit_schema_rule(
    schema: &serde_json::Value,
    rule_name: &str,
    out: &mut String,
    counter: &mut usize,
) {
    // Enum → alternation of JSON-encoded literals.
    if let Some(variants) = schema.get("enum").and_then(|v| v.as_array()) {
        let mut alt = String::new();
        for (i, v) in variants.iter().enumerate() {
            if i > 0 {
                alt.push_str(" | ");
            }
            // JSON-encode then escape for GBNF string literal.
            let s = serde_json::to_string(v).unwrap_or_else(|_| "null".into());
            let gbnf = s.replace('\\', r#"\\"#).replace('"', r#"\""#);
            let _ = write!(alt, r#""{gbnf}""#);
        }
        let _ = writeln!(out, "{rule_name} ::= {alt}");
        return;
    }

    match schema.get("type").and_then(|v| v.as_str()) {
        Some("object") => emit_object_rule(schema, rule_name, out, counter),
        Some("string") => {
            let _ = writeln!(out, "{rule_name} ::= string");
        }
        Some("integer") => {
            // JSON grammar's `number` also permits decimals; reject
            // those for integer fields by forbidding `.` / `e`.
            let _ = writeln!(out, "{rule_name} ::= int_only");
            let _ = writeln!(out, "int_only ::= int");
        }
        Some("number") => {
            let _ = writeln!(out, "{rule_name} ::= number");
        }
        Some("boolean") => {
            let _ = writeln!(out, r#"{rule_name} ::= "true" | "false""#);
        }
        Some("null") => {
            let _ = writeln!(out, r#"{rule_name} ::= "null""#);
        }
        Some("array") => {
            // Items constraint: if `items` is a schema, constrain each
            // element. Otherwise fall back to `value`.
            let items_rule = if let Some(items) = schema.get("items") {
                *counter += 1;
                let name = format!("{rule_name}__item_{c}", c = *counter);
                emit_schema_rule(items, &name, out, counter);
                name
            } else {
                "value".to_string()
            };
            let _ = writeln!(
                out,
                r#"{rule_name} ::= "[" ws ( {items_rule} ( ws "," ws {items_rule} )* )? ws "]""#
            );
        }
        _ => {
            // Unknown / unsupported — accept any JSON value.
            let _ = writeln!(out, "{rule_name} ::= value");
        }
    }
}

fn emit_object_rule(
    schema: &serde_json::Value,
    rule_name: &str,
    out: &mut String,
    counter: &mut usize,
) {
    let props = schema
        .get("properties")
        .and_then(|v| v.as_object())
        .cloned()
        .unwrap_or_default();
    let required: Vec<String> = schema
        .get("required")
        .and_then(|v| v.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default();

    if required.is_empty() {
        // Nothing to pin — accept any object.
        let _ = writeln!(out, "{rule_name} ::= object");
        return;
    }

    // Emit child rules for each required field's schema.
    let mut field_rules: Vec<(String, String)> = Vec::new();
    for name in &required {
        let Some(prop_schema) = props.get(name) else {
            // Required but no schema — accept any value.
            field_rules.push((name.clone(), "value".to_string()));
            continue;
        };
        *counter += 1;
        let child_rule = format!("{rule_name}__{c}", c = *counter);
        emit_schema_rule(prop_schema, &child_rule, out, counter);
        field_rules.push((name.clone(), child_rule));
    }

    // Emit the object rule as a fixed-order sequence. A more flexible
    // implementation would permit any permutation; fixed-order is
    // simpler and the model learns the order from the grammar.
    let mut body = String::from("\"{\" ws");
    for (i, (field_name, child_rule)) in field_rules.iter().enumerate() {
        if i > 0 {
            body.push_str(r#" ws "," ws"#);
        }
        let escaped = field_name.replace('\\', r#"\\"#).replace('"', r#"\""#);
        let _ = write!(body, r#" "\"{escaped}\"" ws ":" ws {child_rule}"#);
    }
    body.push_str(" ws \"}\"");
    let _ = writeln!(out, "{rule_name} ::= {body}");
}

/// Shared JSON value grammar appended to every tool-choice GBNF.
///
/// Handles object / array / string / number / literal, with permissive
/// intra-structure whitespace. Not strict about number formatting edge
/// cases (e.g. `01` is rejected as JSON would); good enough for tool
/// arguments, which downstream parsers will validate.
const JSON_GRAMMAR: &str = r#"
value ::= object | array | string | number | "true" | "false" | "null"
object ::= "{" ws ( member ( ws "," ws member )* )? ws "}"
member ::= string ws ":" ws value
array ::= "[" ws ( value ( ws "," ws value )* )? ws "]"
string ::= "\"" char* "\""
char ::= unescaped | escape
unescaped ::= [^"\\] | [\x20-\x21] | [\x23-\x5B] | [\x5D-\x7F]
escape ::= "\\" ( ["\\/bfnrt] | "u" hex hex hex hex )
hex ::= [0-9a-fA-F]
number ::= int frac? exp?
int ::= "-"? ( "0" | [1-9] [0-9]* )
frac ::= "." [0-9]+
exp ::= [eE] [+\-]? [0-9]+
ws ::= [ \t\n\r]*
"#;

/// Errors from [`grammar_for_tool_choice`].
#[derive(Debug, thiserror::Error)]
pub enum ToolChoiceError {
    #[error("tool list is empty; cannot enforce tool_choice")]
    NoTools,
    #[error("tool_choice picked unknown tool `{0}`")]
    UnknownTool(String),
    #[error(
        "ToolChoice::Any + strict_schema is not supported; use Method when \
         schema enforcement is required"
    )]
    AnyWithStrictSchema,
    #[error("compiled grammar is invalid: {0}")]
    Grammar(#[from] GrammarError),
}

static_assertions::assert_impl_all!(ToolChoiceError: Send, Sync);

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Grammar, GrammarState};
    use serde_json::json;
    use std::{borrow::Cow, sync::Arc};

    fn tool(name: &'static str) -> Tool<'static> {
        Tool {
            name: Cow::Borrowed(name),
            description: Cow::Borrowed(""),
            schema: json!({"type": "object"}),
            cache_control: None,
        }
    }

    fn accepts(src: &str, input: &str) -> bool {
        let grammar = Grammar::parse(src).expect("grammar should parse");
        let mut state = GrammarState::new(Arc::new(grammar));
        state.advance_bytes(input.as_bytes()).is_ok() && state.is_complete()
    }

    #[test]
    fn auto_returns_none() {
        let got = grammar_for_tool_choice(
            &ToolChoice::Auto,
            &[],
            &ToolChoiceOptions::default(),
        )
        .unwrap();
        assert!(got.is_none());
    }

    #[test]
    fn any_rejects_empty_tool_list() {
        let err = grammar_for_tool_choice(
            &ToolChoice::Any,
            &[],
            &ToolChoiceOptions::default(),
        )
        .unwrap_err();
        assert!(matches!(err, ToolChoiceError::NoTools));
    }

    #[test]
    fn method_rejects_unknown_name() {
        let err = grammar_for_tool_choice(
            &ToolChoice::Method {
                name: "missing".into(),
            },
            &[tool("get_weather")],
            &ToolChoiceOptions::default(),
        )
        .unwrap_err();
        assert!(
            matches!(err, ToolChoiceError::UnknownTool(ref n) if n == "missing")
        );
    }

    #[test]
    fn method_grammar_accepts_forced_call() {
        let src = build_grammar_source(
            &["get_weather"],
            None,
            &ToolChoiceOptions::default(),
        );
        assert!(accepts(
            &src,
            r#"{"name": "get_weather", "parameters": {"city": "Paris"}}"#
        ));
        // Other tool names must be rejected.
        assert!(!accepts(
            &src,
            r#"{"name": "send_email", "parameters": {}}"#
        ));
    }

    #[test]
    fn any_grammar_accepts_any_listed_name() {
        let src = build_grammar_source(
            &["a", "b"],
            None,
            &ToolChoiceOptions::default(),
        );
        assert!(accepts(&src, r#"{"name": "a", "parameters": {}}"#));
        assert!(accepts(&src, r#"{"name": "b", "parameters": {}}"#));
        assert!(!accepts(&src, r#"{"name": "c", "parameters": {}}"#));
    }

    #[test]
    fn arguments_field_is_configurable() {
        let opts = ToolChoiceOptions {
            arguments_field: "arguments",
            ..ToolChoiceOptions::default()
        };
        let src = build_grammar_source(&["x"], None, &opts);
        assert!(accepts(&src, r#"{"name": "x", "arguments": {}}"#));
        // With `arguments`, `parameters` is rejected.
        assert!(!accepts(&src, r#"{"name": "x", "parameters": {}}"#));
    }

    #[test]
    fn thought_preamble_optional() {
        let opts = ToolChoiceOptions {
            allow_thought: true,
            ..ToolChoiceOptions::default()
        };
        let src = build_grammar_source(&["x"], None, &opts);
        // No thought.
        assert!(accepts(&src, r#"{"name": "x", "parameters": {}}"#));
        // With thought.
        assert!(accepts(
            &src,
            "<think>I should call x.</think>\n{\"name\": \"x\", \"parameters\": {}}"
        ));
    }

    #[test]
    fn deeply_nested_arguments_accepted() {
        let src =
            build_grammar_source(&["x"], None, &ToolChoiceOptions::default());
        assert!(accepts(
            &src,
            r#"{"name": "x", "parameters": {"a": {"b": [1, 2, {"c": "d"}]}}}"#
        ));
    }

    #[test]
    fn strict_schema_pins_field_names_and_types() {
        let schema_tool = Tool {
            name: Cow::Borrowed("count_letters"),
            description: Cow::Borrowed(""),
            schema: json!({
                "type": "object",
                "properties": {
                    "letter": {"type": "string"},
                    "string": {"type": "string"}
                },
                "required": ["letter", "string"]
            }),
            cache_control: None,
        };
        let opts = ToolChoiceOptions {
            strict_schema: true,
            ..ToolChoiceOptions::default()
        };
        let src =
            build_grammar_source(&["count_letters"], Some(&schema_tool), &opts);
        // Correct shape accepted.
        assert!(accepts(
            &src,
            r#"{"name": "count_letters", "parameters": {"letter": "r", "string": "strawberry"}}"#
        ));
        // Hallucinated field names rejected.
        assert!(!accepts(
            &src,
            r#"{"name": "count_letters", "parameters": {"chr": "r", "str": "strawberry"}}"#
        ));
        // Missing required field rejected.
        assert!(!accepts(
            &src,
            r#"{"name": "count_letters", "parameters": {"letter": "r"}}"#
        ));
        // Wrong type for required field rejected.
        assert!(!accepts(
            &src,
            r#"{"name": "count_letters", "parameters": {"letter": 1, "string": "x"}}"#
        ));
    }

    #[test]
    fn any_plus_strict_schema_errors() {
        let opts = ToolChoiceOptions {
            strict_schema: true,
            ..ToolChoiceOptions::default()
        };
        let err = grammar_for_tool_choice(
            &ToolChoice::Any,
            &[tool("a"), tool("b")],
            &opts,
        )
        .unwrap_err();
        assert!(matches!(err, ToolChoiceError::AnyWithStrictSchema));
    }

    #[test]
    fn malformed_arguments_rejected() {
        let src =
            build_grammar_source(&["x"], None, &ToolChoiceOptions::default());
        // Trailing comma is invalid JSON.
        assert!(!accepts(&src, r#"{"name": "x", "parameters": {"a": 1,}}"#));
        // Single-quoted string is invalid JSON.
        assert!(!accepts(&src, r#"{"name": "x", "parameters": {'a': 1}}"#));
    }

    /// End-to-end: force Llama 3.1 to make a specific tool call. The
    /// grammar constraint should make the generated text parse as
    /// exactly the expected tool call shape.
    #[test]
    #[ignore = "requires model"]
    fn tool_choice_forces_call_against_real_model() {
        use crate::{
            ChatTemplate, Content, Engine, Message, PredictOptions, Prompt,
            RenderOptions, Role, SampleOptions, SamplingMode,
        };
        use std::{num::NonZeroUsize, path::PathBuf};

        let model_path =
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("models/model.gguf");
        let mut engine = Engine::from_path(model_path).unwrap();
        let tmpl = ChatTemplate::from_model(&engine.model).unwrap();

        let weather = tool("get_weather");
        let prompt = Prompt {
            system: Some(Content::SinglePart(Cow::Borrowed(
                "You are a helpful assistant.",
            ))),
            messages: vec![Message {
                role: Role::User,
                content: Content::SinglePart(Cow::Borrowed(
                    "What's the weather in Paris? Call the tool.",
                )),
            }],
            functions: Some(vec![weather.clone()]),
            ..Default::default()
        };
        let rendered = tmpl
            .render_with(
                &prompt,
                &RenderOptions::default().with_generation_prompt(true),
            )
            .unwrap();

        // Build a tool-choice grammar that forces the get_weather call.
        let choice = ToolChoice::Method {
            name: "get_weather".into(),
        };
        let tools = [weather];
        let forced = grammar_for_tool_choice(
            &choice,
            &tools,
            &ToolChoiceOptions::default(),
        )
        .unwrap()
        .expect("Method choice should yield a grammar");

        let tokens = engine.model.tokenize(&rendered, false);
        let mut opts = PredictOptions::default().add_model_stops(&engine.model);
        opts.n = NonZeroUsize::new(256).unwrap();
        opts.sample_options = SampleOptions {
            modes: vec![forced, SamplingMode::locally_typical()],
            ..SampleOptions::default()
        };

        let eos_piece = engine.model.token_to_piece(engine.model.eos());
        let predictor = engine.predict_pieces(tokens, opts);
        let output: String = predictor.collect();

        println!(
            "=== forced tool call ===\n{output}\n========================"
        );
        let _ = eos_piece; // Some tokens render as [Invalid UTF-8] so
                           // trim_end_matches isn't reliable; slice to
                           // the grammar-forced closing brace instead.

        // Slice from the first `{` to the matching `}`. The grammar
        // guarantees a single balanced object.
        let start =
            output.find('{').expect("output must contain opening brace");
        let mut depth = 0;
        let mut end = 0;
        for (i, b) in output[start..].bytes().enumerate() {
            match b {
                b'{' => depth += 1,
                b'}' => {
                    depth -= 1;
                    if depth == 0 {
                        end = start + i + 1;
                        break;
                    }
                }
                _ => {}
            }
        }
        assert!(end > start, "unbalanced braces in output: {output:?}");
        let trimmed = &output[start..end];

        let value: serde_json::Value =
            serde_json::from_str(trimmed).unwrap_or_else(|e| {
                panic!(
                    "forced output must parse as JSON: {e}\noutput: {output:?}\ntrimmed: {trimmed:?}"
                )
            });
        assert_eq!(
            value.get("name").and_then(|v| v.as_str()),
            Some("get_weather"),
            "forced output must have name == get_weather. output: {output:?}"
        );
        assert!(
            value.get("parameters").is_some(),
            "forced output must have a `parameters` field. output: {output:?}"
        );
    }
}
