//! `tool_choice` → [`SamplingMode`] compiler.
//!
//! Takes a [`ToolChoice`] and the advertised [`Tool`] list, emits a GBNF
//! that forces the model's output to match the chosen shape. Rendering is
//! separate: the chat template (via `Prompt::tools`) advertises the tool
//! to the model; this module *enforces* that the model actually calls it.
//!
//! # Shapes currently supported
//!
//! The grammar targets the Llama 3.1 tool-call JSON shape, which is also
//! what HuggingFace's `transformers` tool-calling loop emits by default:
//!
//! ```json
//! {"name": "<function_name>", "parameters": {...}}
//! ```
//!
//! Some shapes (Anthropic, OpenAI) use `"arguments"` instead of
//! `"parameters"`. Configure that via
//! [`ToolChoiceOptions::arguments_field`].
//!
//! # Optional thought preamble
//!
//! Set [`ToolChoiceOptions::allow_thought`] to let the model emit a
//! `<think>…</think>` block *before* the JSON call. Useful for reasoning
//! models; a no-op for templates that don't render thought blocks on
//! re-ingest (Llama 3.1's tool-call branch ignores any surrounding
//! `content`). The grammar accepts a single thought block, then the
//! JSON call. Two balanced tags, no nesting.
//!
//! # Auto
//!
//! [`ToolChoice::Auto`] returns `None` — no sampling constraint is
//! needed because the model is free to call or not call. Pair with
//! `Prompt::tools` to advertise the tools.
//!
//! [`ToolChoice`]: misanthropic::tool::Choice
//! [`Tool`]: crate::Tool
//! [`SamplingMode`]: crate::SamplingMode

use std::fmt::Write;

use crate::grammar_compile::{
    emit_thought_rules, escape_for_gbnf_string, schema_to_gbnf, JSON_GRAMMAR,
};
use crate::{GrammarError, Prompt, SamplingMode, Tool, ToolChoice};

/// Options for [`grammar_for_tool_choice`].
#[derive(Clone, Debug)]
pub struct ToolChoiceOptions {
    /// Permit an optional `<think>…</think>` block before the JSON call.
    /// Generation-time only — survives serialization only if the caller
    /// persists the assistant content themselves.
    pub allow_thought: bool,
    /// Name of the tool-call arguments field. Llama 3.1 and HF use
    /// `"parameters"`. Anthropic / OpenAI function-calling use
    /// `"arguments"`.
    pub arguments_field: &'static str,
    /// Optional `(open, close)` tag pair that wraps the JSON tool call.
    ///
    /// Cogito, Qwen, and Hermes-style templates train the model to emit
    /// `<tool_call>{…}</tool_call>`, not bare JSON. Without the wrapper
    /// in the grammar, the model's first generated byte (`<`) is
    /// rejected and generation force-EOSes.
    ///
    /// Pass `Some(("<tool_call>\n", "\n</tool_call>"))` for cogito /
    /// Qwen-style templates. Leave as `None` for Llama 3.1-style raw
    /// JSON.
    pub wrap_tags: Option<(&'static str, &'static str)>,
    /// If `true`, constrain the arguments object to match the called
    /// tool's `input_schema` rather than accepting any JSON object.
    ///
    /// The schema-to-grammar translator covers the common case:
    /// objects with string / integer / number / boolean / null typed
    /// fields, plus string / integer / number enums. All fields are
    /// required (matches the typical `required: [...]` Anthropic
    /// shape). Unsupported schema features fall back to "any JSON
    /// value". Keep this in mind for complex nested schemas — a model
    /// can still emit a structurally valid but semantically wrong
    /// call.
    ///
    /// Works for both [`ToolChoice::Method`] and [`ToolChoice::Any`].
    /// Under `Any`, the grammar emits one `call_<i>` alternative per
    /// advertised tool, each pinning the literal name to that tool's
    /// schema-derived args rule — so the chosen name and the args
    /// shape stay coupled.
    ///
    /// Defaults to `true`. This diverges from the Anthropic API's
    /// default (no schema enforcement on tool calls), but here it
    /// pays for itself: without it, well-trained models still drop
    /// required fields under sampling pressure (observed: Cogito
    /// emitting `{"comment": "…"}` when `reply_to` was required).
    pub strict_schema: bool,
}

impl Default for ToolChoiceOptions {
    fn default() -> Self {
        Self {
            // Cogito / Qwen / Hermes / DeepSeek-V3 / OpenAI-fn-call
            // shape. The historical Llama-3.1 default
            // (`parameters`, no wrap, no thought) is now the minority
            // case; consumers driving Llama-3.1 should set those
            // explicitly via [`Session::with_tool_choice_opts`].
            allow_thought: true,
            arguments_field: "arguments",
            wrap_tags: Some(("<tool_call>\n", "\n</tool_call>")),
            strict_schema: true,
        }
    }
}

/// Build a [`SamplingMode::Grammar`] that forces the model's output to
/// match the chosen tool-call shape.
///
/// Returns `Ok(None)` for [`ToolChoice::Auto`] — no constraint is
/// appropriate there. For [`ToolChoice::Any`] the grammar accepts any
/// of the tools in `tools`; [`ToolChoice::Method`] pins a specific
/// tool. Returns an error if the chosen tool is not in `tools`, if
/// `tools` is empty (and choice is not `Auto`), or if the generated
/// GBNF fails to compile.
pub fn grammar_for_tool_choice(
    choice: &ToolChoice,
    tools: &[Tool],
    opts: &ToolChoiceOptions,
) -> Result<Option<SamplingMode>, ToolChoiceError> {
    // Resolve which tools the grammar is allowed to pick from. For
    // `Any` that's all advertised tools; for `Method` it's a singleton.
    // `strict_schema` works in both cases — each tool's schema rides
    // along with its name in a per-tool `call_<i>` alternative.
    let chosen: Vec<&Tool> = match choice {
        ToolChoice::Auto => return Ok(None),
        ToolChoice::Any => {
            if tools.is_empty() {
                return Err(ToolChoiceError::NoTools);
            }
            tools.iter().collect()
        }
        ToolChoice::Method { name } => {
            let Some(tool) =
                tools.iter().find(|t| t.name.as_ref() == name.as_str())
            else {
                return Err(ToolChoiceError::UnknownTool(name.clone()));
            };
            vec![tool]
        }
    };

    let source = build_grammar_source(&chosen, opts);
    let mode = SamplingMode::grammar(&source)?;
    Ok(Some(mode))
}

/// Derive the tool-choice grammar directly from a [`Prompt`]. Reads
/// `prompt.tool_choice` and `prompt.functions`; returns `Ok(None)` when
/// the prompt imposes no constraint (no `tool_choice`, `Auto`, or no
/// advertised tools).
///
/// Shorthand for the common case: the same `Prompt` that drives
/// [`ChatTemplate::render`] also drives the sampling constraint.
///
/// [`ChatTemplate::render`]: crate::ChatTemplate::render
pub fn grammar_for_prompt(
    prompt: &Prompt,
    opts: &ToolChoiceOptions,
) -> Result<Option<SamplingMode>, ToolChoiceError> {
    let Some(choice) = prompt.tool_choice.as_ref() else {
        return Ok(None);
    };
    let tools: &[Tool] = prompt.functions.as_deref().unwrap_or(&[]);
    grammar_for_tool_choice(choice, tools, opts)
}

/// Debug-only accessor for the compiled GBNF text. Kept public so the
/// `strawberry` example can `--verbose` the grammar; callers generally
/// don't need this.
#[doc(hidden)]
pub fn build_grammar_source_for_debug(
    tools: &[&Tool],
    opts: &ToolChoiceOptions,
) -> String {
    build_grammar_source(tools, opts)
}

/// Emit the GBNF source text for a tool-choice constraint.
///
/// Each tool in `tools` becomes one `call_<i>` alternative under the
/// outer `call` rule, pinning the literal `name` to that tool. When
/// [`ToolChoiceOptions::strict_schema`] is true, each `call_<i>`
/// references its own `args_<i>` rule derived from the tool's
/// `input_schema`; otherwise all alternatives share the permissive
/// `object` rule from [`JSON_GRAMMAR`]. Per-tool alternatives are what
/// let `strict_schema` work under [`ToolChoice::Any`] — name and args
/// shape stay coupled.
///
/// Kept pub(crate) + exposed through tests so the generated grammar can
/// be inspected directly without constructing a full [`SamplingMode`].
pub(crate) fn build_grammar_source(
    tools: &[&Tool],
    opts: &ToolChoiceOptions,
) -> String {
    let mut src = String::with_capacity(1024);

    // Root rule: optional thought block, then (optionally wrapped) call.
    let wrapped_call = if opts.wrap_tags.is_some() {
        "wrapped_call"
    } else {
        "call"
    };
    if opts.allow_thought {
        let _ = writeln!(src, "root ::= thought? ws {wrapped_call}");
        emit_thought_rules(&mut src);
    } else {
        let _ = writeln!(src, "root ::= ws {wrapped_call}");
    }
    if let Some((open, close)) = opts.wrap_tags {
        // LlamaCppModel emits `<open>\n{…}\n</close>` in its trained format.
        // We accept any whitespace around the JSON to tolerate minor
        // layout drift. The literal tag text is escaped to survive
        // being embedded in a GBNF string literal.
        let open_lit = escape_for_gbnf_string(open);
        let close_lit = escape_for_gbnf_string(close);
        let _ = writeln!(
            src,
            r#"wrapped_call ::= "{open_lit}" ws call ws "{close_lit}""#
        );
    }

    // Outer call wraps the JSON braces; per-tool alternatives carry the
    // name + args body.
    let mut alts = String::new();
    for i in 0..tools.len() {
        if i > 0 {
            alts.push_str(" | ");
        }
        let _ = write!(alts, "call_{i}");
    }
    let _ = writeln!(src, r#"call ::= "{{" ws ( {alts} ) ws "}}""#);

    // Pipeline for embedded JSON literals: `serde_json::to_string`
    // produces a JSON string literal with JSON escapes (handles control
    // chars, `\`, `"`, non-ASCII). We then GBNF-escape that literal so
    // it survives being embedded inside a GBNF `"..."` terminal.
    let arg_field_lit = {
        let json_lit = serde_json::to_string(opts.arguments_field).unwrap();
        escape_for_gbnf_string(&json_lit)
    };
    for (i, tool) in tools.iter().enumerate() {
        let name_lit = {
            let json_lit = serde_json::to_string(tool.name.as_ref()).unwrap();
            escape_for_gbnf_string(&json_lit)
        };
        let args_rule: String = if opts.strict_schema {
            format!("args_{i}")
        } else {
            "object".into()
        };
        let _ = writeln!(
            src,
            r#"call_{i} ::= "\"name\"" ws ":" ws "{name_lit}" ws "," ws "{arg_field_lit}" ws ":" ws {args_rule}"#,
        );
    }

    // Schema-derived args rules, one per tool. Skipped when strict
    // schema is off — `object` from JSON_GRAMMAR covers the permissive
    // case.
    if opts.strict_schema {
        for (i, tool) in tools.iter().enumerate() {
            schema_to_gbnf(&tool.schema, &format!("args_{i}"), &mut src);
        }
    }

    // Standard JSON grammar — RFC 8259-ish, enough for tool arguments.
    src.push_str(JSON_GRAMMAR);

    src
}

/// Errors from [`grammar_for_tool_choice`].
#[derive(Debug, thiserror::Error)]
pub enum ToolChoiceError {
    #[error("tool list is empty; cannot enforce tool_choice")]
    NoTools,
    #[error("tool_choice picked unknown tool `{0}`")]
    UnknownTool(String),
    #[error("compiled grammar is invalid: {0}")]
    Grammar(#[from] GrammarError),
}

static_assertions::assert_impl_all!(ToolChoiceError: Send, Sync);

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Grammar, GrammarState};
    use serde_json::json;
    use std::{borrow::Cow, sync::Arc};

    fn tool(name: &'static str) -> Tool {
        Tool {
            name: Cow::Borrowed(name),
            description: Cow::Borrowed(""),
            schema: json!({"type": "object"}),
            cache_control: None,
            strict: None,
        }
    }

    /// Legacy Llama-3.1 tool-call shape (`parameters`, no envelope, no
    /// thought, no schema enforcement). The crate-wide
    /// `ToolChoiceOptions::default()` now targets the Cogito/Qwen
    /// envelope shape; tests that assert against bare JSON pin the
    /// older shape locally so they don't drift with the default.
    fn bare_opts() -> ToolChoiceOptions {
        ToolChoiceOptions {
            allow_thought: false,
            arguments_field: "parameters",
            wrap_tags: None,
            strict_schema: false,
        }
    }

    fn accepts(src: &str, input: &str) -> bool {
        let grammar = Grammar::parse(src).expect("grammar should parse");
        let mut state = GrammarState::new(Arc::new(grammar));
        state.advance_bytes(input.as_bytes()).is_ok() && state.is_complete()
    }

    #[test]
    fn auto_returns_none() {
        let got = grammar_for_tool_choice(
            &ToolChoice::Auto,
            &[],
            &ToolChoiceOptions::default(),
        )
        .unwrap();
        assert!(got.is_none());
    }

    #[test]
    fn any_rejects_empty_tool_list() {
        let err = grammar_for_tool_choice(
            &ToolChoice::Any,
            &[],
            &ToolChoiceOptions::default(),
        )
        .unwrap_err();
        assert!(matches!(err, ToolChoiceError::NoTools));
    }

    #[test]
    fn method_rejects_unknown_name() {
        let err = grammar_for_tool_choice(
            &ToolChoice::Method {
                name: "missing".into(),
            },
            &[tool("get_weather")],
            &ToolChoiceOptions::default(),
        )
        .unwrap_err();
        assert!(
            matches!(err, ToolChoiceError::UnknownTool(ref n) if n == "missing")
        );
    }

    #[test]
    fn method_grammar_accepts_forced_call() {
        let t = tool("get_weather");
        let src = build_grammar_source(&[&t], &bare_opts());
        assert!(accepts(
            &src,
            r#"{"name": "get_weather", "parameters": {"city": "Paris"}}"#
        ));
        // Other tool names must be rejected.
        assert!(!accepts(
            &src,
            r#"{"name": "send_email", "parameters": {}}"#
        ));
    }

    #[test]
    fn any_grammar_accepts_any_listed_name() {
        let a = tool("a");
        let b = tool("b");
        let src = build_grammar_source(&[&a, &b], &bare_opts());
        assert!(accepts(&src, r#"{"name": "a", "parameters": {}}"#));
        assert!(accepts(&src, r#"{"name": "b", "parameters": {}}"#));
        assert!(!accepts(&src, r#"{"name": "c", "parameters": {}}"#));
    }

    #[test]
    fn arguments_field_is_configurable() {
        let opts = ToolChoiceOptions {
            arguments_field: "arguments",
            ..bare_opts()
        };
        let t = tool("x");
        let src = build_grammar_source(&[&t], &opts);
        assert!(accepts(&src, r#"{"name": "x", "arguments": {}}"#));
        // With `arguments`, `parameters` is rejected.
        assert!(!accepts(&src, r#"{"name": "x", "parameters": {}}"#));
    }

    #[test]
    fn thought_preamble_optional() {
        let opts = ToolChoiceOptions {
            allow_thought: true,
            ..bare_opts()
        };
        let t = tool("x");
        let src = build_grammar_source(&[&t], &opts);
        // No thought.
        assert!(accepts(&src, r#"{"name": "x", "parameters": {}}"#));
        // With thought.
        assert!(accepts(
            &src,
            "<think>I should call x.</think>\n{\"name\": \"x\", \"parameters\": {}}"
        ));
    }

    #[test]
    fn deeply_nested_arguments_accepted() {
        let t = tool("x");
        let src = build_grammar_source(&[&t], &bare_opts());
        assert!(accepts(
            &src,
            r#"{"name": "x", "parameters": {"a": {"b": [1, 2, {"c": "d"}]}}}"#
        ));
    }

    #[test]
    fn strict_schema_pins_field_names_and_types() {
        let schema_tool = Tool {
            name: Cow::Borrowed("count_letters"),
            description: Cow::Borrowed(""),
            schema: json!({
                "type": "object",
                "properties": {
                    "letter": {"type": "string"},
                    "string": {"type": "string"}
                },
                "required": ["letter", "string"]
            }),
            cache_control: None,
            strict: None,
        };
        let opts = ToolChoiceOptions {
            strict_schema: true,
            ..bare_opts()
        };
        let src = build_grammar_source(&[&schema_tool], &opts);
        // Correct shape accepted.
        assert!(accepts(
            &src,
            r#"{"name": "count_letters", "parameters": {"letter": "r", "string": "strawberry"}}"#
        ));
        // Hallucinated field names rejected.
        assert!(!accepts(
            &src,
            r#"{"name": "count_letters", "parameters": {"chr": "r", "str": "strawberry"}}"#
        ));
        // Missing required field rejected.
        assert!(!accepts(
            &src,
            r#"{"name": "count_letters", "parameters": {"letter": "r"}}"#
        ));
        // Wrong type for required field rejected.
        assert!(!accepts(
            &src,
            r#"{"name": "count_letters", "parameters": {"letter": 1, "string": "x"}}"#
        ));
    }

    /// `ToolChoice::Any` with `strict_schema = true`: the grammar must
    /// emit per-tool alternatives so each name is paired with its own
    /// schema-derived args rule. A name from tool A cannot ride along
    /// with tool B's args shape (or vice versa).
    #[test]
    fn any_plus_strict_schema_couples_name_to_args() {
        let tool_a = Tool {
            name: Cow::Borrowed("a"),
            description: Cow::Borrowed(""),
            schema: json!({
                "type": "object",
                "properties": {"x": {"type": "integer"}},
                "required": ["x"]
            }),
            cache_control: None,
            strict: None,
        };
        let tool_b = Tool {
            name: Cow::Borrowed("b"),
            description: Cow::Borrowed(""),
            schema: json!({
                "type": "object",
                "properties": {"y": {"type": "string"}},
                "required": ["y"]
            }),
            cache_control: None,
            strict: None,
        };
        let opts = ToolChoiceOptions {
            strict_schema: true,
            ..bare_opts()
        };
        let src = build_grammar_source(&[&tool_a, &tool_b], &opts);

        // Each tool's name accepts its own args.
        assert!(accepts(&src, r#"{"name": "a", "parameters": {"x": 1}}"#));
        assert!(accepts(&src, r#"{"name": "b", "parameters": {"y": "hi"}}"#));
        // Cross-pairing rejected: name a + b's args, or name b + a's
        // args — these are exactly the failure mode the per-tool
        // alternatives prevent.
        assert!(!accepts(
            &src,
            r#"{"name": "a", "parameters": {"y": "hi"}}"#
        ));
        assert!(!accepts(&src, r#"{"name": "b", "parameters": {"x": 1}}"#));
        // Unknown name rejected.
        assert!(!accepts(&src, r#"{"name": "c", "parameters": {"x": 1}}"#));
        // grammar_for_tool_choice path (with default opts) also
        // succeeds — no AnyWithStrictSchema error.
        let res =
            grammar_for_tool_choice(&ToolChoice::Any, &[tool_a, tool_b], &opts);
        assert!(res.is_ok(), "Any+strict_schema must compile, got {res:?}");
    }

    #[test]
    fn malformed_arguments_rejected() {
        let t = tool("x");
        let src = build_grammar_source(&[&t], &bare_opts());
        // Trailing comma is invalid JSON.
        assert!(!accepts(&src, r#"{"name": "x", "parameters": {"a": 1,}}"#));
        // Single-quoted string is invalid JSON.
        assert!(!accepts(&src, r#"{"name": "x", "parameters": {'a': 1}}"#));
    }

    // ======================================================================
    // Regression locks for bugs fixed in Phase 0.5.1
    // ======================================================================

    /// Regression lock for the `int_only ::= int` duplicate-rule bug.
    /// Before the fix, any schema with ≥2 integer fields failed to
    /// compile at `Grammar::parse` as a duplicate-rule syntax error.
    #[test]
    fn strict_schema_two_integer_fields_compiles() {
        let schema_tool = Tool {
            name: Cow::Borrowed("two_ints"),
            description: Cow::Borrowed(""),
            schema: json!({
                "type": "object",
                "properties": {
                    "x": {"type": "integer"},
                    "y": {"type": "integer"}
                },
                "required": ["x", "y"]
            }),
            cache_control: None,
            strict: None,
        };
        let opts = ToolChoiceOptions {
            strict_schema: true,
            ..bare_opts()
        };
        // Compilation must succeed — the previous bug errored here.
        let result = grammar_for_tool_choice(
            &ToolChoice::Method {
                name: "two_ints".into(),
            },
            &[schema_tool.clone()],
            &opts,
        );
        assert!(
            result.is_ok(),
            "two-integer schema must compile, got {:?}",
            result.err()
        );
        // And the grammar must still accept valid inputs and reject
        // decimals.
        let src = build_grammar_source(&[&schema_tool], &opts);
        assert!(accepts(
            &src,
            r#"{"name": "two_ints", "parameters": {"x": 1, "y": 2}}"#
        ));
        assert!(!accepts(
            &src,
            r#"{"name": "two_ints", "parameters": {"x": 1.5, "y": 2}}"#
        ));
    }

    /// Regression lock for `think_char ::= [^<]`. Before the fix, a
    /// thought containing `<` (e.g. `if x < 5`) would force-EOS.
    #[test]
    fn thought_body_with_lt_inside_accepted() {
        let opts = ToolChoiceOptions {
            allow_thought: true,
            ..bare_opts()
        };
        let t = tool("x");
        let src = build_grammar_source(&[&t], &opts);
        assert!(accepts(
            &src,
            "<think>if x < 5 then call x</think>\n{\"name\": \"x\", \"parameters\": {}}"
        ));
    }

    /// Regression lock for the hand-rolled escape path. A tool name
    /// containing JSON-escapable characters must embed through the
    /// grammar without blowing up the GBNF parser.
    #[test]
    fn tool_name_with_special_chars_embeds_safely() {
        // A tool name with a backslash and a quote.
        let weird_tool = Tool {
            name: Cow::Borrowed("evil\\\"name"),
            description: Cow::Borrowed(""),
            schema: json!({"type": "object"}),
            cache_control: None,
            strict: None,
        };
        let src = build_grammar_source(&[&weird_tool], &bare_opts());
        // Grammar compiles.
        assert!(
            Grammar::parse(&src).is_ok(),
            "grammar failed to parse for weird name:\n{src}"
        );
        // And it accepts the properly JSON-escaped tool call.
        let json_name =
            serde_json::to_string(weird_tool.name.as_ref()).unwrap();
        let input = format!(r#"{{"name": {json_name}, "parameters": {{}}}}"#);
        assert!(accepts(&src, &input));
    }

    // ======================================================================
    // wrap_tags gap-fill (previously ZERO tests — cogito production path)
    // ======================================================================

    #[test]
    fn wrap_tags_accepts_tagged_envelope() {
        let opts = ToolChoiceOptions {
            wrap_tags: Some(("<tool_call>\n", "\n</tool_call>")),
            ..bare_opts()
        };
        let t = tool("x");
        let src = build_grammar_source(&[&t], &opts);
        assert!(accepts(
            &src,
            "<tool_call>\n{\"name\": \"x\", \"parameters\": {}}\n</tool_call>"
        ));
    }

    #[test]
    fn wrap_tags_rejects_bare_json() {
        let opts = ToolChoiceOptions {
            wrap_tags: Some(("<tool_call>\n", "\n</tool_call>")),
            ..bare_opts()
        };
        let t = tool("x");
        let src = build_grammar_source(&[&t], &opts);
        // With wrap_tags on, bare JSON without the envelope must be
        // rejected.
        assert!(!accepts(&src, r#"{"name": "x", "parameters": {}}"#));
    }

    #[test]
    fn wrap_tags_rejects_mismatched_tags() {
        let opts = ToolChoiceOptions {
            wrap_tags: Some(("<tool_call>\n", "\n</tool_call>")),
            ..bare_opts()
        };
        let t = tool("x");
        let src = build_grammar_source(&[&t], &opts);
        // Wrong close tag.
        assert!(!accepts(
            &src,
            "<tool_call>\n{\"name\": \"x\", \"parameters\": {}}\n</wrong>"
        ));
        // Missing close.
        assert!(!accepts(
            &src,
            "<tool_call>\n{\"name\": \"x\", \"parameters\": {}}"
        ));
    }

    #[test]
    fn wrap_tags_plus_thought_composition() {
        // The cogito:14b production triple: thought preamble + tagged
        // envelope.
        let opts = ToolChoiceOptions {
            allow_thought: true,
            wrap_tags: Some(("<tool_call>\n", "\n</tool_call>")),
            ..bare_opts()
        };
        let t = tool("x");
        let src = build_grammar_source(&[&t], &opts);
        assert!(accepts(
            &src,
            "<think>plan the call</think>\n<tool_call>\n{\"name\": \"x\", \"parameters\": {}}\n</tool_call>"
        ));
        // Thought alone (no call) must still be rejected — the call
        // is required.
        assert!(!accepts(&src, "<think>just thinking</think>"));
    }

    // ======================================================================
    // allow_thought edge cases
    // ======================================================================

    #[test]
    fn thought_unclosed_rejected() {
        let opts = ToolChoiceOptions {
            allow_thought: true,
            ..bare_opts()
        };
        let t = tool("x");
        let src = build_grammar_source(&[&t], &opts);
        assert!(!accepts(
            &src,
            r#"<think>never closed {"name": "x", "parameters": {}}"#
        ));
    }

    #[test]
    fn thought_after_json_rejected() {
        let opts = ToolChoiceOptions {
            allow_thought: true,
            ..bare_opts()
        };
        let t = tool("x");
        let src = build_grammar_source(&[&t], &opts);
        // Thought after the JSON is not in the grammar.
        assert!(!accepts(
            &src,
            r#"{"name": "x", "parameters": {}}<think>too late</think>"#
        ));
    }

    #[test]
    fn empty_thought_accepted() {
        let opts = ToolChoiceOptions {
            allow_thought: true,
            ..bare_opts()
        };
        let t = tool("x");
        let src = build_grammar_source(&[&t], &opts);
        assert!(accepts(
            &src,
            r#"<think></think>{"name": "x", "parameters": {}}"#
        ));
    }

    // ======================================================================
    // strict_schema per-primitive-type coverage
    // ======================================================================

    fn single_required_schema(field: &str, prop: serde_json::Value) -> Tool {
        Tool {
            name: Cow::Borrowed("fn"),
            description: Cow::Borrowed(""),
            schema: json!({
                "type": "object",
                "properties": { field: prop },
                "required": [field]
            }),
            cache_control: None,
            strict: None,
        }
    }

    #[test]
    fn strict_schema_integer_rejects_decimals_and_exponents() {
        let t = single_required_schema("n", json!({"type": "integer"}));
        let opts = ToolChoiceOptions {
            strict_schema: true,
            ..bare_opts()
        };
        let src = build_grammar_source(&[&t], &opts);
        assert!(accepts(&src, r#"{"name": "fn", "parameters": {"n": 42}}"#));
        assert!(accepts(&src, r#"{"name": "fn", "parameters": {"n": -7}}"#));
        assert!(!accepts(
            &src,
            r#"{"name": "fn", "parameters": {"n": 1.5}}"#
        ));
        assert!(!accepts(
            &src,
            r#"{"name": "fn", "parameters": {"n": 1e10}}"#
        ));
    }

    #[test]
    fn strict_schema_number_accepts_decimals_and_exponents() {
        let t = single_required_schema("n", json!({"type": "number"}));
        let opts = ToolChoiceOptions {
            strict_schema: true,
            ..bare_opts()
        };
        let src = build_grammar_source(&[&t], &opts);
        assert!(accepts(&src, r#"{"name": "fn", "parameters": {"n": 42}}"#));
        assert!(accepts(&src, r#"{"name": "fn", "parameters": {"n": 1.5}}"#));
        assert!(accepts(
            &src,
            r#"{"name": "fn", "parameters": {"n": -0.5e3}}"#
        ));
        assert!(!accepts(
            &src,
            r#"{"name": "fn", "parameters": {"n": "x"}}"#
        ));
    }

    #[test]
    fn strict_schema_boolean_forces_true_false() {
        let t = single_required_schema("b", json!({"type": "boolean"}));
        let opts = ToolChoiceOptions {
            strict_schema: true,
            ..bare_opts()
        };
        let src = build_grammar_source(&[&t], &opts);
        assert!(accepts(
            &src,
            r#"{"name": "fn", "parameters": {"b": true}}"#
        ));
        assert!(accepts(
            &src,
            r#"{"name": "fn", "parameters": {"b": false}}"#
        ));
        assert!(!accepts(
            &src,
            r#"{"name": "fn", "parameters": {"b": "true"}}"#
        ));
        assert!(!accepts(&src, r#"{"name": "fn", "parameters": {"b": 1}}"#));
    }

    #[test]
    fn strict_schema_null_forces_null() {
        let t = single_required_schema("z", json!({"type": "null"}));
        let opts = ToolChoiceOptions {
            strict_schema: true,
            ..bare_opts()
        };
        let src = build_grammar_source(&[&t], &opts);
        assert!(accepts(
            &src,
            r#"{"name": "fn", "parameters": {"z": null}}"#
        ));
        assert!(!accepts(&src, r#"{"name": "fn", "parameters": {"z": 0}}"#));
    }

    #[test]
    fn strict_schema_string_enum_variants() {
        let t = single_required_schema(
            "color",
            json!({"type": "string", "enum": ["red", "green", "blue"]}),
        );
        let opts = ToolChoiceOptions {
            strict_schema: true,
            ..bare_opts()
        };
        let src = build_grammar_source(&[&t], &opts);
        assert!(accepts(
            &src,
            r#"{"name": "fn", "parameters": {"color": "red"}}"#
        ));
        assert!(accepts(
            &src,
            r#"{"name": "fn", "parameters": {"color": "blue"}}"#
        ));
        assert!(!accepts(
            &src,
            r#"{"name": "fn", "parameters": {"color": "yellow"}}"#
        ));
    }

    #[test]
    fn strict_schema_integer_enum_variants() {
        let t = single_required_schema(
            "level",
            json!({"type": "integer", "enum": [1, 2, 3]}),
        );
        let opts = ToolChoiceOptions {
            strict_schema: true,
            ..bare_opts()
        };
        let src = build_grammar_source(&[&t], &opts);
        assert!(accepts(
            &src,
            r#"{"name": "fn", "parameters": {"level": 1}}"#
        ));
        assert!(!accepts(
            &src,
            r#"{"name": "fn", "parameters": {"level": 4}}"#
        ));
        assert!(!accepts(
            &src,
            r#"{"name": "fn", "parameters": {"level": "1"}}"#
        ));
    }

    #[test]
    fn strict_schema_array_of_strings() {
        let t = single_required_schema(
            "tags",
            json!({"type": "array", "items": {"type": "string"}}),
        );
        let opts = ToolChoiceOptions {
            strict_schema: true,
            ..bare_opts()
        };
        let src = build_grammar_source(&[&t], &opts);
        assert!(accepts(
            &src,
            r#"{"name": "fn", "parameters": {"tags": ["a", "b"]}}"#
        ));
        assert!(accepts(
            &src,
            r#"{"name": "fn", "parameters": {"tags": []}}"#
        ));
        assert!(!accepts(
            &src,
            r#"{"name": "fn", "parameters": {"tags": [1, 2]}}"#
        ));
        assert!(!accepts(
            &src,
            r#"{"name": "fn", "parameters": {"tags": "a"}}"#
        ));
    }

    #[test]
    fn strict_schema_nested_object() {
        let t = Tool {
            name: Cow::Borrowed("fn"),
            description: Cow::Borrowed(""),
            schema: json!({
                "type": "object",
                "properties": {
                    "loc": {
                        "type": "object",
                        "properties": {
                            "x": {"type": "integer"},
                            "y": {"type": "integer"}
                        },
                        "required": ["x", "y"]
                    }
                },
                "required": ["loc"]
            }),
            cache_control: None,
            strict: None,
        };
        let opts = ToolChoiceOptions {
            strict_schema: true,
            ..bare_opts()
        };
        let src = build_grammar_source(&[&t], &opts);
        assert!(accepts(
            &src,
            r#"{"name": "fn", "parameters": {"loc": {"x": 1, "y": 2}}}"#
        ));
        assert!(!accepts(
            &src,
            r#"{"name": "fn", "parameters": {"loc": {"x": 1}}}"#
        ));
        assert!(!accepts(
            &src,
            r#"{"name": "fn", "parameters": {"loc": "origin"}}"#
        ));
    }

    // ======================================================================
    // grammar_for_prompt early-return paths
    // ======================================================================

    #[test]
    fn grammar_for_prompt_no_tool_choice_returns_none() {
        use crate::Prompt;
        let prompt = Prompt {
            tool_choice: None,
            ..Default::default()
        };
        let got =
            grammar_for_prompt(&prompt, &ToolChoiceOptions::default()).unwrap();
        assert!(got.is_none());
    }

    #[test]
    fn grammar_for_prompt_auto_returns_none() {
        use crate::Prompt;
        let prompt = Prompt {
            tool_choice: Some(ToolChoice::Auto),
            functions: Some(vec![tool("x")]),
            ..Default::default()
        };
        let got =
            grammar_for_prompt(&prompt, &ToolChoiceOptions::default()).unwrap();
        assert!(got.is_none());
    }

    /// End-to-end: force Llama 3.1 to make a specific tool call. The
    /// grammar constraint should make the generated text parse as
    /// exactly the expected tool call shape.
    #[cfg(feature = "llama-cpp")]
    #[test]
    #[ignore = "requires model"]
    fn tool_choice_forces_call_against_real_model() {
        use crate::{
            ChatTemplate, Content, Engine, Message, PredictOptions, Prompt,
            RenderOptions, Role, SampleOptions, SamplingMode,
        };
        use std::{num::NonZeroUsize, path::PathBuf};

        let model_path =
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("models/model.gguf");
        let mut engine = Engine::from_path(model_path).unwrap();
        let tmpl = ChatTemplate::from_model(&engine.model).unwrap();

        let weather = tool("get_weather");
        let prompt = Prompt {
            system: Some(Content::SinglePart(Cow::Borrowed(
                "You are a helpful assistant.",
            ))),
            messages: vec![Message {
                role: Role::User,
                content: Content::SinglePart(Cow::Borrowed(
                    "What's the weather in Paris? Call the tool.",
                )),
            }],
            functions: Some(vec![weather.clone()]),
            ..Default::default()
        };
        let rendered = tmpl
            .render_with(
                &prompt,
                &RenderOptions::default().with_generation_prompt(true),
            )
            .unwrap();

        // Build a tool-choice grammar that forces the get_weather call.
        let choice = ToolChoice::Method {
            name: "get_weather".into(),
        };
        let tools = [weather];
        let forced = grammar_for_tool_choice(
            &choice,
            &tools,
            &ToolChoiceOptions::default(),
        )
        .unwrap()
        .expect("Method choice should yield a grammar");

        let tokens = engine.model.tokenize(&rendered, false);
        let mut opts = PredictOptions::default().add_model_stops(&engine.model);
        opts.n = NonZeroUsize::new(256).unwrap();
        opts.sample_options = SampleOptions {
            modes: vec![forced, SamplingMode::locally_typical()],
            ..SampleOptions::default()
        };

        let eos_piece = engine.model.token_to_piece(engine.model.eos());
        let predictor = engine.predict_pieces(tokens, opts);
        let output: String = predictor.collect();

        println!(
            "=== forced tool call ===\n{output}\n========================"
        );
        let _ = eos_piece; // Some tokens render as [Invalid UTF-8] so
                           // trim_end_matches isn't reliable; slice to
                           // the grammar-forced closing brace instead.

        // Slice from the first `{` to the matching `}`. The grammar
        // guarantees a single balanced object.
        let start =
            output.find('{').expect("output must contain opening brace");
        let mut depth = 0;
        let mut end = 0;
        for (i, b) in output[start..].bytes().enumerate() {
            match b {
                b'{' => depth += 1,
                b'}' => {
                    depth -= 1;
                    if depth == 0 {
                        end = start + i + 1;
                        break;
                    }
                }
                _ => {}
            }
        }
        assert!(end > start, "unbalanced braces in output: {output:?}");
        let trimmed = &output[start..end];

        let value: serde_json::Value =
            serde_json::from_str(trimmed).unwrap_or_else(|e| {
                panic!(
                    "forced output must parse as JSON: {e}\noutput: {output:?}\ntrimmed: {trimmed:?}"
                )
            });
        assert_eq!(
            value.get("name").and_then(|v| v.as_str()),
            Some("get_weather"),
            "forced output must have name == get_weather. output: {output:?}"
        );
        assert!(
            value.get("parameters").is_some(),
            "forced output must have a `parameters` field. output: {output:?}"
        );
    }
}
